version: "3.8"

services:
  app:
    container_name: app
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
    networks:
      - app
    restart: unless-stopped
networks:
  app:
    driver: bridge
